# Generated by Django 5.1.5 on 2025-03-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='follower',
        ),
        migrations.AddField(
            model_name='myuser',
            name='instaHandle',
            field=models.CharField(default='demo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='linkedinHandle',
            field=models.CharField(default='demo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MyUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(blank=True)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('availability', models.CharField(blank=True, max_length=50)),
                ('salary_expectations', models.CharField(blank=True, max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('achievements_certifications', models.JSONField(default=list)),
                ('interests', models.JSONField(default=list)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], default='Other', max_length=10)),
                ('pronouns', models.CharField(choices=[('she/her', 'She/Her'), ('he/him', 'He/Him'), ('they/them', 'They/Them'), ('Other', 'Other')], default='Other', max_length=10)),
                ('veteran', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('disability', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('ethnicity', models.CharField(choices=[('Asian', 'Asian'), ('White', 'White'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Other', 'Other')], default='Other', max_length=30)),
                ('remote_work', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('in_person_work', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('open_to_relocation', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('willing_to_complete_assessments', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('willing_to_undergo_drug_tests', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('willing_to_undergo_background_checks', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('proficiency', models.CharField(max_length=50)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='base.myuserdata')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='base.myuserdata')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='base.myuserdata')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_link', models.URLField(blank=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='base.myuserdata')),
            ],
        ),
    ]
