# Generated by Django 5.1.5 on 2025-03-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='instaHandle',
            field=models.CharField(default='demo', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='linkedinHandle',
            field=models.CharField(default='demo', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
