# Generated by Django 5.1.5 on 2025-03-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_myuser_follower_myuser_instahandle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
    ]
